# 202235203 고수호
# **3week - wine.csv 데이터에 대한 Classification**

# **# 데이터 세트 불러오기**
`import pandas as pd` : 데이터를 표(Table) 형태로 다루기 위한 **Pandas** 라이브러리.  
`import numpy as np` : 수치 계산 및 행렬 연산을 위한 **NumPy** 라이브러리.  
`path = '/content/drive/MyDrive/Colab Notebooks/3week/wine.csv'` : 데이터 파일이 저장된 경로를 문자열 변수 '**path**'에 저장.  
`df = pd.read_csv(path)` : 읽어온 데이터는 데이터프레임 형태로 변수 '**df**'에 저장.

In [26]:
import pandas as pd
import numpy as np
path = '/content/drive/MyDrive/Colab Notebooks/3week/wine.csv'
df = pd.read_csv(path)

df

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

# **# 데이터 전처리(y)**
`y = df['Wine']` : 예측하고자 하는 목표 변수(와인 종류)를 변수 '**y**'에 저장.  
`y.value_counts()` : 각 와인 클래스별 데이터 개수를 확인.

In [27]:
y = df['Wine']
y.value_counts()

Wine
2    71
1    59
3    48
Name: count, dtype: int64

# **# 데이터 전처리(X)**
`X = df.drop('Wine', axis=1)` : 전체 데이터에서 '**Wine**' 열을 제외한 나머지 특징들을 변수 '**X**'에 저장.  
`X.head()` : 분리된 특징 데이터의 상위 5개 행을 확인.

In [28]:
X=df.drop('Wine',axis=1)
X.head()

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

# **# 데이터셋 분리 (Training & Test Set)**
`from sklearn.model_selection import train_test_split` : 데이터를 나누기 위한 사이킷런의 함수.  
`test_size=0.25` : 전체 데이터의 **25%** 를 평가용(Test)으로, **75%** 를 학습용(Train)으로 설정.  
`random_state=0` : 실행할 때마다 동일한 결과가 나오도록 난수 시드 고정.

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.25,random_state=0)

# **# 모델별 학습 및 평가 1 - 로지스틱 회귀 (Logistic Regression)**
**선형 회귀 방식을 분류에 적용한 알고리즘으로, 클래스에 속할 확률을 계산.**  
`clf_lr = LogisticRegression(random_state=0)` : 1. **로지스틱 회귀** 모델 객체 생성.  
`clf_lr.fit(X_train, y_train)` : 2. 학습 데이터(**X_train**)와 그에 맞는 정답(**y_train**)을 모델에게 주어 관계를 파악하는 방식으로 학습.    
`pred_lr = clf_lr.predict(X_test)` : 3. 학습된 모델을 사용하여 테스트 데이터(**X_test**)에 대한 예측을 수행.  
`print (accuracy_score(y_test, pred_lr))` : 4. 전체 예측 중 맞춘 비율인 정확도(**Accuracy**) 출력. (0~1 사이 값).     
`print (confusion_matrix(y_test, pred_lr))` : 5. 모델이 정답을 어떻게 틀렸는지 세부 정보를 보여주는 오차 행렬(**Confusion Matrix**) 출력.

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(X_train, y_train)

pred_lr = clf_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

# **# 모델별 학습 및 평가 2 - 결정 트리 (Decision Tree)**
**데이터의 특징을 기준으로 '예/아니오' 질문을 던져 데이터를 분류하는 나무 형태의 모델.**  
`clf_dt = DecisionTreeClassifier(random_state=0)` : 1. **의사결정나무** 모델 객체를 생성.  
`clf_dt.fit(X_train, y_train)` : 2. 학습 데이터(**X_train**)와 정답(**y_train**) 사이의 규칙을 학습하여 트리 구조를 형성하는 방식.    
`pred_dt = clf_dt.predict(X_test)` : 3. 학습된 모델을 사용하여 테스트 데이터(**X_test**)에 대한 예측을 수행.  
`print (accuracy_score(y_test, pred_dt))` : 4. 전체 예측 중 맞춘 비율인 정확도(**Accuracy**) 출력. (0~1 사이 값).     
`print (confusion_matrix(y_test, pred_dt))` : 5. 모델이 정답을 어떻게 틀렸는지 세부 정보를 보여주는 오차 행렬(**Confusion Matrix**) 출력.

In [31]:
clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(X_train, y_train)

pred_dt = clf_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.9333333333333333
[[14  2  0]
 [ 0 20  1]
 [ 0  0  8]]

# **# 모델별 학습 및 평가 3 - 랜덤 포레스트 (Random Forest)**
**여러 개의 결정 트리를 생성하고, 그 결과들을 종합하여 예측 성능을 높이는 방식.**  
`clf_dt = DecisionTreeClassifier(random_state=0)` : 1. **랜덤 포레스트** 모델 객체를 생성.  
`clf_dt.fit(X_train, y_train)` : 2. 학습 데이터(**X_train**)와 정답(**y_train**) 모델에 넣어 나무를 만드는 방식으로 학습.    
`pred_dt = clf_dt.predict(X_test)` : 3. 학습된 모델을 사용하여 테스트 데이터(**X_test**)에 대한 예측을 수행.  
`print (accuracy_score(y_test, pred_dt))` : 4. 전체 예측 중 맞춘 비율인 정확도(**Accuracy**) 출력. (0~1 사이 값).     
`print (confusion_matrix(y_test, pred_dt))` : 5. 모델이 정답을 어떻게 틀렸는지 세부 정보를 보여주는 오차 행렬(**Confusion Matrix**) 출력.

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(X_train, y_train)

pred = rf_clf.predict(X_test)

print ("\n--- Random Forest ---")
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Random Forest ---
0.9777777777777777
[[16  0  0]
 [ 0 20  1]
 [ 0  0  8]]

# **# 모델별 학습 및 평가 4 - kNN 알고리즘 (k-Nearest Neighbor)**
**새로운 데이터가 들어왔을 때, 가장 가까운 $k$개의 이웃 데이터를 확인하여 더 많은 쪽으로 분류하는 방식.**  
`knn = KNeighborsClassifier(n_neighbors=6)` : 1. 새로운 데이터를 분류할 때 참고할 이웃의 개수를 **6개**로 설정.  
`knn.fit(X_train, y_train)` : 2. 학습 데이터(**X_train**)와 정답(**y_train**)을 사용하여 모델을 학습.  
`pred_y = knn.predict(X_test)` : 3. 학습된 모델을 사용하여 테스트 데이터(**X_test**)에 대한 예측을 수행.  
`accuracy_score(y_test, pred_y)` : 4. 전체 예측 중 맞춘 비율인 정확도(**Accuracy**) 출력. (0~1 사이 값).     
`print (confusion_matrix(y_test, pred_y))` : 5. 모델이 정답을 어떻게 틀렸는지 세부 정보를 보여주는 오차 행렬(**Confusion Matrix**) 출력.

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train, y_train)

pred_y = knn.predict(X_test)

print ("\n--- kNN ---")
print (accuracy_score(y_test,pred_y))
print (confusion_matrix(y_test, pred_y))

--- kNN ---
0.7111111111111111
[[14  0  2]
 [ 0 16  5]
 [ 2  4  2]]